### ISSUE TITLE
BeatAML SMILES missing

### ISSUE THREAD

**Issue by SafiaSafa** [bhklab/ORCESTRA#29]
Hello,

I am using the `PharmacoGx` R package to acces the BeatAML dataset. For the other datasets in PharmacoGx there is SMILES associated to each compound but it's not the case for BeatAML. Since the `PSets` in PharmacoGx are version controlled via ORCESTRA, I am reaching you for help. Is there a way to have acces to this information?

**Comment by ChristopherEeles** [comment]
Hi @SafiaSafa,

I think maybe I misunderstood your question. I thought that you had used BeatAML in the past and at that time it had SMILES in the drug annotations but that those SMILES are no longer present. If that is the case then this issue stands.

If it is not the case, it may simply be that the publication did not include this information, and thus it is not present in the BeatAML dataset. If this is the case, I recommend looking the drugs up in PubChem or ChEMBL to find the smiles.

I believe both of these sites have batch query interfaces through the web browser.

Best,
Chris

**Comment by ChristopherEeles** [comment]
Hi @SafiaSafa,

We never heard back from you on this issue. If you still have questions feel free to re-open it.

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN
